### ISSUE TITLE
shuffle doesnt work

### ISSUE THREAD

**Issue by kvbappinio** [httpete-ire/typer#10]
Shuffle doestn work for me. 
Its set to "true" - but does not shuffle

**Comment by httpete-ire** [comment]
Are you passing a boolean or a string to the shuffle attribute?

for example this works

```
shuffle="true"
```

but this doesnt 

```
shuffle="'true'"
```

I'll alter it to except either a boolean or a string value

**Comment by httpete-ire** [comment]
@kvbappinio just pushed a fix that will accept a boolean or a string representation of a boolean

**Comment by kvbappinio** [comment]
thanks, but this doesnt work either. I put the words in the typer tag - there not in a json or so. 
Maybe thats the reason ? Everything else works fine

e.g.
  <typer  words="[
          'test1',
          'test2',
          'test3'
          ]"
                 type-time="100"
                 backspace-time='50'
                 start-delay='2000'
                 cursor=""
                 shuffle="true"
                 start-typing="true"></typer> 

am i missing something ?

**Comment by httpete-ire** [comment]
Sorry about that, thought I fixed it. I'll have a look into this now.

What version of angular are you using? Any errors in the console?

**Comment by httpete-ire** [comment]
@kvbappinio ok I think I have it sorted now. Can you check the latest version please

**Comment by kvbappinio** [comment]
Its working now - thanks alot ;)
