### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by MikaAK** [httpete-ire/typer#11]
For those who use webpack it would be incredibly usefull if this was published on NPM. Unfortunatly a typer package already exists on npm so this would have to have a seperate name on npm.

**Comment by kvbappinio** [comment]
//signed - would be nice to have it in npm

**Comment by httpete-ire** [comment]
Published this to NPM. As @MikaAK mentioned, a typer package already exists so I named this __angular-typer__

Thanks for the suggestion :+1:
