### ISSUE TITLE
First word should also be typed

### ISSUE THREAD

**Issue by fclaussen** [httpete-ire/typer#2]
I have intentions to use it with small sentences instead of just words and it would be awesome if the first sentence / word would also show up one letter at a time.

Right now it shows up the entire thing, then deletes and start typing the next word.

**Comment by httpete-ire** [comment]
Thanks for your feedback, I could add an option that would allow the user to set whether the word should type out first or delete first.

**Comment by httpete-ire** [comment]
credit to @jvandemo for his suggestion on setting the initial value
