### ISSUE TITLE
Additional Feature: As an Input Placeholder

### ISSUE THREAD

**Issue by JSlifierz** [httpete-ire/typer#3]
Not sure if the implementation is already possible, but my immediate thought was that this would be very useful for search suggestions in our app's search feature. Thus, a directive that replaces, but acts as, an input's placeholder would be perfect.

**Comment by httpete-ire** [comment]
I'm not 100% sure I know what you mean, something that autocompletes the word as you type? similar to how google does this https://support.google.com/websearch/answer/106230?hl=en

Too be honest I don't think this fits into the scope of this library, for now I'm going to close this issue. If have misunderstood you I will be happy to reopen the issue and take a look at the implementing it

Thanks for your feedback :+1:

**Comment by JSlifierz** [comment]
Looking back, I can see how my original suggestion wasn't clear. My apologies.

I don't mean to suggest autocomplete. I mean for this feature to be possible as the placeholder attribute of an input tag (*<input type="text" name="query" placeholder="Search the entire database">*). Right now, placeholders are static. We build a tool for scientists that allows them to query large datasets. We like to use the placeholder attribute as a medium for giving suggestions on *how* someone can search the database. However, I could see this feature making that placeholder attribute dynamic. We could use it to give search suggestions, so *before* the user has began typing their query, and *not* as an autocomplete.

Hope that's more clear. Essentially, a dynamic placeholder for input tags. Up to you to decide if this is implementable or within scope.

Good work thus far!

**Comment by httpete-ire** [comment]
@JSlifierz no need to apologise at all. Now I understand what you mean, I'm not sure if it possible to implement it using the current placeholder attribute on an input.

However I did manage to get a quick demo of what you are looking for using the current implementation. It uses css positioning to place the 'typer' directive over an input. http://plnkr.co/edit/fNIS5jx53R6nHJTHuLji?p=preview 

Few things you would need to do, handle hiding the typing effect when the input is focused, also show the typer when the user clicks away from the input without entering any value.

Hope that helps and thanks for your feedback!!!

If you find an easier way to do what you are looking for please let me know

:+1:

**Comment by JSlifierz** [comment]
@httpete-ire your suggestion is probably the right way to go. I just finished creating an Angular directive that does just what you suggested. Will just apply the typer directive to this scenario.

Awesome.
