### ISSUE TITLE
Laggy typing effect on iOS

### ISSUE THREAD

**Issue by rarkins** [httpete-ire/typer#6]
I've found that the typing effect is abnormally laggy on iOS, producing much slower effect than desktop or even low end Android. My observations are:

Desktop: fine (baseline)
Android default browser: it "skips"/groups letter animations if typing speed is high, but it's tolerable
iOS (Safari, Chrome, and iPhone + iPad): The effect is correct (types/backspaces every letter) but s...l...o...w...l...y compared to desktop

You can see it here for now: http://staging.keylocation.sg

**Comment by httpete-ire** [comment]
Unfortunately I cant test it on android as I dont have access to an android device

I have tested it on iPhone 5s and yes you are right it is very laggy when the page initially loads. However if you scroll down the page and then back up the typer performs as expected.  

It seems that iOS delays the execution of JavaScript timers when the page is not focused (user has not interacted with it at all). see http://stackoverflow.com/questions/6543325/what-happens-to-javascript-execution-settimeout-etc-when-iphone-android-goes

I'll leave the issue open incase anyone has a suggestion on how to fix this
